# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:        
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Publish Artifacts
        uses: actions/upload-artifact@v1.0.0
        with:
          name: webapp
          path: ${{ github.workspace }}/app