# This is a basic workflow to help you get started with Actions

name: CI

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:        
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set env
        run: echo "appSettings_calphicert=MIIF1TCCA72gAwIBAgIUUCFK1ZC8ruQHhZaFw5fReALuTXQwDQYJKoZIhvcNAQELBQAwXDELMAkGA1UEBhMCVVMxIzAhBgNVBAoMGkFsbHNjcmlwdHMgSGVhbHRoY2FyZSBMTEMuMSgwJgYDVQQDDB9BbGxzY3JpcHRzIFByaXZhdGUgU2lnbmluZyBDQSAxMB4XDTIyMDMyOTEzMzk0NloXDTI0MDMyOTE0NDkwMFowgbQxHzAdBgNVBAMMFnNoaWVsZHRlc3QtYXVwLXNpZ25pbmcxOzA5BgNVBAsMMlZBTElEQVRFRCAtIEFkdmFuY2VkIENlcnRpZnlJRCBEaWdpdGFsIENlcnRpZmljYXRlMSIwIAYDVQQKDBlBbGxzY3JpcHRzIEhlYWx0aGNhcmUgTExDMRAwDgYDVQQHDAdDaGljYWdvMREwDwYDVQQIDAhJbGxpbm9pczELMAkGA1UEBhMCVVMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDTshPL9sLGIAAr0AqGGrQkkOZb+SNq+O0Fo4l/3o/o/X6Au96zHqF+W6rhhp6V2/7xDPNePl9hu1KxoWo/DY3uzOIYL+H+f1woRuIPrJTUWWcM4HWzDFiAPz9k5Zw9EsgjCykuBaf+JqZI6mrKKQc4pyKXHVMH7InKlro3niE2gYb7QqCqZqG+5lI4HgfWmigp1pA+8L89iEYs9Bj6k94yrCSuxxIEdMk4I753pEcCGL+q3+EGc4hVgN6ycr2K4GTr5CAFS2eRvabSjcD6xW2Gq5u0vVg8vuMU3aIJo/mvql8VPvUGFqJtYfdbkzEvufa+EBbOSbqaSf6DkmUO8tgNAgMBAAGjggE0MIIBMDAMBgNVHRMBAf8EAjAAMB8GA1UdIwQYMBaAFL4HrgIGWBqAt5vu/uHdUanBQNghMHUGCCsGAQUFBwEBBGkwZzA9BggrBgEFBQcwAoYxaHR0cDovL3BraS5hbGxzY3JpcHRzLmNvbS9jcnQvYWxscHZ0c2lnbmluZ18xLmNydDAmBggrBgEFBQcwAYYaaHR0cDovL29jc3AuYWxsc2NyaXB0cy5jb20wQgYDVR0fBDswOTA3oDWgM4YxaHR0cDovL3BraS5hbGxzY3JpcHRzLmNvbS9jcmwvYWxscHZ0c2lnbmluZ18xLmNybDAdBgNVHQ4EFgQUsf7vf0u4FYSq/B7/OnCUitnSOi0wFQYDVR0lBA4wDAYKKwYBBAGCNwoDDDAOBgNVHQ8BAf8EBAMCB4AwDQYJKoZIhvcNAQELBQADggIBAAL+QozFsm7Us9icIefBvfu4B52YwFFG8n4ei0fx2vJ/uk3MYcAzMs+wYY8JzGTT5a6Llikd1C4y6jlH8WQwXvvwt5RDZhJL4F9Prxm1z6fBsRnBFCPOvVE5TKuK96K6jjV+e5tQzZBliRVgESUFZYRLX9eyXq/hG9QYqNU2ZyUXxFuqSIwa0ALNnll40N3+IvDMC0Yjt+vN5P0fVc9ZNvSTxl+I+4GwMSUi+GZHxn+IMLqbYUMq1p17A1s98zu5LBahLyo8MYH3Yma5foDk+cZqZV5jgFuB+9dFnuR0cacT7nqgrwCHQjV0tsdUbGb1MuGegvhlDd4Xh0VQ+84txReVH6uAlQ1+D9fvy5fp4XV0wYhFtwpfWww+vZyzSK/Mx4wwnp9oZu8ZHSdBTWhATgQF+iD+4VwblspXJlxo80lFfmd+WGX5kZewFA89tIrLNioLrE7DOaL+tRRIR1rNY8CqaOM0RAMkUZMZCt5+sQ6lQFhfmbbAxaGLOLIZ9LTW7RUjqWlLtq/e0oiTH/dMK//UAfmxG6xl73F2zPU4IaAGRgkAEWRm5K/SG396LL3thh52jt9FpfwIjQO9xPE6IdWfIK7ogCpJ5oHPPjrM9Eld9xUbruvmTAka6k9SFETeZMUqUV6MiEC8THFSTvJtkivYTiAQz+RLn4lUhteQ3tLi" >> $GITHUB_ENV
      
      - name: Test
        run: echo $appSettings_calphicert

      - name: Publish Artifacts
        uses: actions/upload-artifact@v1.0.0
        with:
          name: webapp
          path: ${{ github.workspace }}/params