# This is a basic workflow to help you get started with Actions

name: CI

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:        
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set env
        run: echo "appSettings_calphicert=MIIDETCCAfmgAwIBAgIUGsVx/PeowvMnF543y0QBTgc7ROIwDQYJKoZIhvcNAQELBQAwGDEWMBQGA1UEAwwNQmlmcm9zdENsaWVudDAeFw0yMTA4MDQxNDU1MThaFw0yMjA4MDQxNDU1MThaMBgxFjAUBgNVBAMMDUJpZnJvc3RDbGllbnQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC3abrQ7X77HR0P7TODneRWJFpi9Tybxfwlh/N1nMeVrbrNoxhtfT9edcuDeQLev35ia7cIYBQgBD59LHbNSvi/Qm0zhl1I/b4AYLf2FOTJv49yWYG6673rYI1eqa/1/IyZMsufiQpPoQ+ozsOzlytUDRxrgAkx5o+nKdDYnOgptHl4NEdil3zXhqHpDmIao//23qbWFDOP5f6AMArjHSYUnprRam5coSAFa7sCTwIXzDTnbjB+/oWMFyEqm5/T0tIXzp4M2lKuzpegRSvWqZItMQ4WeJkbR5QdYVAh90BU/IOzdcn6PDTp4yFgJtpdx2PIoslpYkE1GQ0ihFEshhTXAgMBAAGjUzBRMB0GA1UdDgQWBBQir9ImBbBaCndGg3z/8Yi5ea2s4DAfBgNVHSMEGDAWgBQir9ImBbBaCndGg3z/8Yi5ea2s4DAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQA4Yv/AnmGIecYVSuicsjODtNWbL8SJ4SK2X+cZiRQd5czN+0LSGAHFdtbNtCTI8+ouDxFb6J4GY0IAeIqeDxDE1plmnU8ddBsJY/o6WwZx5v+opjoS0i8MH02PkPmCaOLXwGTgKTA3Ndi8TzV9DlitsxpnDYAGHx3TZnSowXmTop2B7weB6xmcvlPW6TeA8aqaKyqFQuyGdX55x4oby03dFWHuOv0ygHWhN3/5Ko8kht+244ZXKeuWDE+rjSfQNxbv+JdhZmluvNeeoVpivc2xKdHuy/B5ETBE1IIfyNM/Jlg93PoUPxD+tyjNfT8Piif1U85DG+ef6B/gm94zbv73" >> $GITHUB_ENV
      
      - name: Test
        run: echo $appSettings_calphicert

      - name: Publish Artifacts
        uses: actions/upload-artifact@v1.0.0
        with:
          name: webapp
          path: ${{ github.workspace }}/params