name: deploy-ftr

on:
  workflow_run:
    workflows: [deploy-ftr]
    types:
      - completed

jobs:

  deploy-ftr:
    uses: kgparmar739/workflow-dispatch/.github/workflows/template/deployment.yml@main
    with:
      env_name: sit
      ci_workflow_run_id: context.payload.workflow_run.id
  