name: deploy-int

on:
  workflow_run:
    workflows: [deploy-ftr]
    branches: [main]
    types:
      - completed

jobs:

  deploy-int:
    uses: kgparmar739/workflow-dispatch/.github/workflows/deployment.yml@main
    with:
      env_name: int
      ci_workflow_run_id: context.payload.workflow_run.id
  