name: deploy-sit

on:
  workflow_run:
    workflows: [deploy-ftr,CI]
    types: [completed]

jobs:

  deploy-sit:
    uses: kgparmar739/workflow-dispatch/.github/workflows/deployment.yml@main
    with:
      env_name: sit
      ci_workflow_run_id: context.payload.workflow_run.id
  