name: rollback-sit

on:
  workflow_run:
    workflows: [deploy-sit]
    types: [completed]

jobs:

  rollback-sit:
    uses: kgparmar739/workflow-dispatch/.github/workflows/rollback.yml@main
    with:
      env_name: sit