name: rollback-int

on:
  workflow_run:
    workflows: [deploy-int]
    branches: [main]
    types:
      - completed

jobs:

  rollback-int:
    uses: kgparmar739/workflow-dispatch/.github/workflows/rollback.yml@main
    with:
      env_name: int