name: rollback-ftr

on:
  workflow_run:
    workflows: [deploy-ftr]
    branches: [features/*]
    types:
      - completed

jobs:

  rollback-ftr:
    uses: kgparmar739/workflow-dispatch/.github/workflows/rollback.yml@main
    with:
      env_name: ftr